### ISSUE TITLE
dependency i18next-conv

### ISSUE THREAD

**Issue by d0whc3r** [dotcore64/rollup-plugin-i18next-conv#5]
Add i18next-conv as depedency insteat of "devDependency" because it is needed to use the plugin

**Comment by perrin4869** [comment]
@d0whc3r It's a `peerDependency` right now... I think I should update the `README.md` to make it clearer

**Comment by d0whc3r** [comment]
well, I installed and rollup build was fail for missing dependency

**Comment by perrin4869** [comment]
hm... I think when you installed, `npm` would have put up a warning that you are missing `i18next-conv`, but let me update the `README.md` with the correct installation instructions

**Comment by perrin4869** [comment]
Pushed 499ae9c455efe2039bb69789db82daefbeadfe2d
